api_type: openai
batch_size: 100
chunk_overlap: 200
chunk_size: 1000
cache_dir: .cache
db_path: chunks.db
cosinus_index: 0.5
embedding_model: paraphrase-multilingual-MiniLM-L12-v2
max_workers: 12
merge_cosinus_threshold: 0.7
output_dir: _ai_merged
semantic_threshold: 0.7
path_threshold: 6
top_results: 10
temperature: 0.2
timeout: 6000
vault_path: /home/dima/MyAI/chuncker/springer_textbook
api_key: "API_KEY"
openai_model: "gpt-4o"
